---
title: Comparisson Between a Trained Model With Parsimonius Data and EHR Data (Such
  as MIMIC-III)
output: pdf_document
---

## Set enviroment variables

```{r echo=F results='hide'}
Sys.setenv(DATABASECONNECTOR_JAR_FOLDER = '/home/ohdsi/drivers')
```

## Change working directory

```{r echo=F results='hide'}
expected_wd = '/home/ohdsi/workdir/src'

if (getwd() != expected_wd){
  setwd(cat(getwd(), '/workdir/src/'))  
}
```

## Connect to PostgreSQL MIMIC-III Database

```{r echo=T}
pathToDriver = Sys.getenv('DATABASECONNECTOR_JAR_FOLDER')

DatabaseConnector::downloadJdbcDrivers(dbms = 'postgresql', pathToDriver = pathToDriver)

connectionDetails <- DatabaseConnector::createConnectionDetails(
  dbms = 'postgresql',  
  user = 'postgres', 
  password = 'securepass321.',
  server = 'mimic-server.postgres.database.azure.com/mimic',
  port = 5432,
  extraSettings = 'ssl=true;',
  pathToDriver = pathToDriver
)

input_schema = 'omop'
output_schema = 'edangulo_demar'

connection <- DatabaseConnector::connect(connectionDetails)

dbListTables(connection, schema = input_schema)
```

```{r echo=T, results='hide'}
DatabaseConnector::querySql(connection, 'SELECT * FROM omop.drug_exposure LIMIT 5')
```

## Define Cohorts

```{r echo=T}
cdmDatabaseSchema = 'omop'
resultsDatabaseSchema = 'edangulo_demar'

sql <- SqlRender::readSql('cohortsOfInterest.sql')
sql <- SqlRender::render(sql, input_schema = input_schema, output_schema = output_schema)
sql <- SqlRender::translate(sql, targetDialect = 'postgresql')

DatabaseConnector::executeSql(connection, sql)
```

```{r}
sql <- paste('SELECT cohort_definition_id, COUNT(*) AS count',
             'FROM @output_schema.heart_disease',
             'GROUP BY cohort_definition_id')

sql <- SqlRender::render(sql, output_schema = output_schema)
sql <- SqlRender::translate(sql, targetDialect = connectionDetails$dbms)

DatabaseConnector::querySql(connection, sql)
```

```{r}
sql <- paste('SELECT * FROM @output_schema.heart_disease LIMIT 5')

sql <- SqlRender::render(sql, output_schema = output_schema)
sql <- SqlRender::translate(sql, targetDialect = connectionDetails$dbms)

DatabaseConnector::querySql(connection, sql)
```

## Feature Extraction

```{r echo=T}
library(FeatureExtraction)

covariateSettings <- FeatureExtraction::createDefaultCovariateSettings()

covariateData <- FeatureExtraction::getDbCovariateData(
  connectionDetails = connectionDetails,
  cdmDatabaseSchema = input_schema,
  cohortDatabaseSchema = output_schema,
  cohortTable = 'heart_disease',
  cohortId = 321588,
  rowIdField = 'subject_id',
  covariateSettings = covariateSettings
)

summary(covariateData)
```

### Per-person Covariates

Show Tables for per-person covariates

```{r echo=T, results='hide'}
show(covariateData)
```

Features for per-person covariates

```{r echo=T, results='hide'}
covariateData$covariateRef
```

```{r echo=T, results='hide'}
covariateData$covariates
```
```{r}
write.csv(covariateData$analysisRef , paste0(getwd(), '/../output/analysisRef.csv'), row.names = FALSE)
```

```{r}
write.csv(covariateData$covariateRef, paste0(getwd(), '/../output/covariateRef.csv'), row.names = FALSE)
```

```{r}
write.csv(covariateData$covariates, paste0(getwd(), '/../output/covariates.csv'), row.names = FALSE)
```
